# ⚠️  BUSINESS RULES - VALIDACIONES OBLIGATORIAS Y ORDEN ESTRICTO
# CRÍTICO: Estas reglas DEBEN aplicarse en el orden exacto especificado
# El LLM NO puede saltarse ninguna validación ni interpretarlas de forma creativa

# 🔒 ORDEN DE VALIDACIÓN OBLIGATORIO (FAIL-FAST)
# El LLM DEBE evaluar en este orden exacto y RECHAZAR inmediatamente si falla cualquier paso
validation_order:
  1: "user_existence_check"      # ❌ Usuario debe existir en DB
  2: "subscription_status_check" # ❌ Subscription_active DEBE ser true
  3: "payment_status_check"      # ❌ Monthly_fee_current DEBE ser true  
  4: "show_matching_check"       # ❌ Debe encontrar show con fuzzy >= threshold
  5: "show_availability_check"   # ❌ Remaining_discounts DEBE ser > 0
  6: "duplicate_request_check"   # ❌ No debe haber solicitud previa aprobada
  7: "date_validity_check"       # ❌ Show debe estar en rango de fechas válido

# 🚨 CRITICAL FAIL CONDITIONS - AUTOMATIC REJECTION
# Si cualquiera de estas condiciones es true → RECHAZO INMEDIATO
critical_fails:
  user_not_found:
    condition: "user_data is None or user_data == {}"
    message: "Email no registrado en el sistema"
    action: "IMMEDIATE_REJECT"
    
  subscription_inactive:
    condition: "user_data.subscription_active == false"
    message: "Suscripción inactiva"
    action: "IMMEDIATE_REJECT"
    
  payments_overdue:
    condition: "user_data.monthly_fee_current == false"
    message: "Cuotas mensuales atrasadas - debe ponerse al día antes de solicitar descuentos"
    action: "IMMEDIATE_REJECT"
    
  no_show_match:
    condition: "matching_shows is empty or best_similarity < fuzzy_threshold"
    message: "No se encontró show que coincida con la descripción"
    action: "IMMEDIATE_REJECT"
    
  no_discounts_available:
    condition: "show.remaining_discounts <= 0 or show.max_discounts <= 0"
    message: "Descuentos agotados para este show"
    action: "IMMEDIATE_REJECT"
    
  duplicate_request:
    condition: "previous_request_exists == true and previous_approved == true"
    message: "Ya existe una solicitud aprobada para este show"
    action: "IMMEDIATE_REJECT"

# 📋 VALIDATION RULES - CONFIGURACIÓN DETALLADA
user_validation:
  subscription_required: true
  monthly_fee_required: true
  email_exact_match: true
  case_sensitive: false
  
discount_rules:
  max_per_user_per_show: 1
  min_days_before_show: 1   
  max_days_before_show: 90
  default_discount_percentage: 15
  
show_matching:
  fuzzy_threshold: 0.8      # Mínimo 80% de similitud
  required_fields: ["artist", "venue", "title"]
  city_matching: true
  max_matches_to_consider: 3
  
# 🎯 LLM BEHAVIOR CONFIGURATION
llm_instructions:
  decision_style: "STRICT_BUSINESS_RULES"
  reasoning_style: "STEP_BY_STEP_VALIDATION" 
  language: "spanish"
  tone: "professional"
  
  # 🚨 CRITICAL: Instrucciones que el LLM NO puede ignorar
  mandatory_behavior:
    - "ALWAYS check validation_order sequentially"
    - "NEVER skip critical_fail conditions"
    - "REJECT immediately on any critical_fail"
    - "DO NOT be creative with rule interpretation"
    - "monthly_fee_current=false ALWAYS means REJECT"
    - "remaining_discounts=0 ALWAYS means REJECT"
    - "Focus on business rules BEFORE user preferences"
    
  # ✅ Approval requirements (ALL must be true)
  approval_requirements:
    - "user_exists == true"
    - "subscription_active == true" 
    - "monthly_fee_current == true"
    - "show_found == true"
    - "remaining_discounts > 0"
    - "no_previous_approved_request == true"
    - "show_date_in_valid_range == true"

# 📝 RESPONSE TEMPLATES
rejection_messages:
  user_not_found: "El email {email} no está registrado en nuestro sistema. Por favor verifique el email o regístrese primero."
  subscription_inactive: "Su suscripción no está activa. Active su suscripción para solicitar descuentos."
  fees_not_current: "Tiene cuotas mensuales pendientes. Regularice su situación de pagos para acceder a descuentos."
  show_not_found: "No encontramos un show que coincida con '{show_description}'. Verifique el nombre del artista o show."
  no_discounts_available: "Los descuentos para '{show_title}' están agotados. No hay más cupos disponibles."
  previous_request_exists: "Ya tiene una solicitud de descuento aprobada para '{show_title}'. Solo se permite un descuento por usuario por show."
  show_date_invalid: "El show '{show_title}' está fuera del rango de fechas válido para solicitar descuentos."

approval_message_template: "Solicitud aprobada para '{show_title}' - {show_artist}. Descuento: {discount_percentage}%. Instrucciones: {discount_instructions}"

# 🔧 DEBUG AND MONITORING
monitoring:
  log_all_decisions: true
  log_llm_reasoning: true
  track_rejection_reasons: true
  confidence_threshold_warning: 0.7 